#
# Module manifest for module 'OllamaOpenWebUIAPI'
#
# Generated by: adjiap
#
# Generated on: 20/07/2025
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'OllamaOpenWebUIAPI.psm1'

    # Version number of this module.
    ModuleVersion = '0.0.1'

    # ID used to uniquely identify this module
    GUID = '8a9519f4-5cfc-4e6f-8700-0cf4cbbb34a7'

    # Author of this module
    Author = 'adjiap'

    # Company or vendor of this module
    CompanyName = 'adjiap'

    # Copyright statement for this module
    Copyright = '(c) adjiap. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'PowerShell module for interacting with Ollama and Open WebUI API'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Functions to export from this module
    FunctionsToExport = @(
        'Invoke-OllamaChat',
        'Invoke-OllamaChatBatch', 
        'Start-OllamaChatConversation',
        'Get-AvailableOllamaModels'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = @()

    # Private data to pass to the module
    PrivateData = @{
        PSData = @{
            # Tags applied to this module
            Tags = @('Ollama', 'OpenWebUI', 'API', 'AI', 'LLM')

            # A URL to the license for this module
            LicenseUri = 'https://github.com/adjiap/OllamaOpenWebUIAPI/blob/main/LICENSE'

            # A URL to the main website for this project
            ProjectUri = 'https://github.com/adjiap/OllamaOpenWebUIAPI'

            # Release notes
            ReleaseNotes = 'Initial release of OllamaOpenWebUIAPI module'
        }
    }
}